"""
===============================================================================
AI TOOLING & DEVELOPMENT DOCUMENTATION
===============================================================================
1. AI Tools Used:
   - ChatGPT / OpenAI Codex: Initial scaffolding of the Streamlit layout and 
     Fanning/Darcy friction factor algorithms.
   - Claude 3.5 Sonnet: Generating interactive Plotly charts, modular architecture,
     and robust error handling blocks.

2. Key Prompts Given:
   - "Create a Streamlit application calculating fluid pressure drop in a 
      pipe using Darcy-Weisbach with inputs for flow rate, pipe diameter, 
      density, viscosity, and pipe roughness."
   - "Add a Plotly visualization showing pressure drop versus pipe diameter 
      across a user-defined range, updating dynamically with input controls."
   - "Implement dynamic error handling so zero or negative pipe dimensions, 
      viscosity, or flow rates trigger st.warning without throwing Python runtime exceptions."

3. Important Manual Fixes & Verifications:
   - Separated UI frontend logic (app.py) from hydraulic computational models (engineering.py).
   - Fixed Reynolds number calculation units: Streamlit inputs were initially 
     in standard metric (mm diameter, cP viscosity), causing the friction factor 
     equation to fail due to unit mismatch. Manually converted inputs into strict 
     SI units (meters and Pa·s) before applying the Colebrook-White / Swamee-Jain equation.
   - Verified that the Swamee-Jain explicit approximation accurately matches standard 
     Moody diagram values within a <0.5% error tolerance.
===============================================================================
"""

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

# Import physics/hydraulics calculations from custom engineering module
from engineering import calculate_flow_hydraulics, generate_diameter_sensitivity

# -----------------------------------------------------------------------------
# PAGE CONFIGURATION & HEADER
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Fluid Flow & Pressure Drop Analyser",
    page_icon="🌊",
    layout="wide"
)

st.title("🌊 Fluid Flow & Pressure Drop Analyser")
st.subheader("Interactive Hydraulic Analysis & Moody Diagram Flow Regime Evaluation")

st.markdown("""
Welcome to the Fluid Flow & Pressure Drop Analyser! This tool calculates hydraulic parameters for incompressible fluid flow in circular pipes using the Darcy-Weisbach formulation and Swamee-Jain friction factor equation.

### 📋 Instructions:
1. Adjust the fluid properties and pipe geometry using the Sidebar Controls on the left.
2. View real-time results, flow regime classification, and friction factor calculations in the summary panel.
3. Explore the Interactive Plot to see how changing pipe diameter impacts pressure loss.
4. Review and download the calculated parametric table generated by Pandas.
""")

st.divider()

# -----------------------------------------------------------------------------
# SIDEBAR CONTROLS (At least 3 interactive controls)
# -----------------------------------------------------------------------------
st.sidebar.header("⚙️ Flow & Pipe Parameters")

# Control 1: Flow Rate Slider
flow_rate_m3h = st.sidebar.slider(
    label="Volumetric Flow Rate (m³/h)",
    min_value=0.0,
    max_value=500.0,
    value=50.0,
    step=2.5,
    help="Select the volumetric flow rate passing through the pipe."
)

# Control 2: Pipe Internal Diameter Number Input
pipe_diameter_mm = st.sidebar.number_input(
    label="Pipe Inner Diameter (mm)",
    min_value=0.0,
    max_value=1000.0,
    value=100.0,
    step=5.0,
    help="Specify the internal diameter of the pipe."
)

# Control 3: Pipe Material Selectbox
pipe_material = st.sidebar.selectbox(
    label="Pipe Material (Roughness ε)",
    options=[
        "Commercial Steel (ε = 0.045 mm)",
        "Ductile Iron (ε = 0.260 mm)",
        "PVC / Plastic (ε = 0.0015 mm)",
        "Concrete (ε = 1.000 mm)",
        "Custom Roughness"
    ],
    index=0
)

# Handle custom roughness selection
if "Commercial Steel" in pipe_material:
    roughness_mm = 0.045
elif "Ductile Iron" in pipe_material:
    roughness_mm = 0.26
elif "PVC" in pipe_material:
    roughness_mm = 0.0015
elif "Concrete" in pipe_material:
    roughness_mm = 1.0
else:
    roughness_mm = st.sidebar.number_input("Custom Roughness ε (mm)", min_value=0.0001, value=0.05, step=0.01)

# Additional Fluid Inputs
st.sidebar.subheader("💧 Fluid Properties")
fluid_density = st.sidebar.number_input("Fluid Density (kg/m³)", min_value=0.1, value=998.2, step=10.0)
fluid_viscosity_cp = st.sidebar.number_input("Dynamic Viscosity (cP)", min_value=0.01, value=1.00, step=0.1)
pipe_length_m = st.sidebar.slider("Pipe Length (m)", min_value=1.0, max_value=2000.0, value=100.0, step=10.0)

# -----------------------------------------------------------------------------
# ERROR HANDLING BLOCK
# -----------------------------------------------------------------------------
is_valid = True

if flow_rate_m3h <= 0:
    st.warning("⚠️ Volumetric flow rate must be strictly greater than 0 m³/h.")
    is_valid = False

if pipe_diameter_mm <= 0:
    st.warning("⚠️ Pipe inner diameter must be strictly greater than 0 mm.")
    is_valid = False

if fluid_density <= 0:
    st.warning("⚠️ Fluid density must be greater than 0 kg/m³.")
    is_valid = False

if fluid_viscosity_cp <= 0:
    st.warning("⚠️ Dynamic viscosity must be greater than 0 cP.")
    is_valid = False

# -----------------------------------------------------------------------------
# CALCULATION & RESULTS DISPLAY
# -----------------------------------------------------------------------------
if is_valid:
    # Compute hydraulics using module
    results = calculate_flow_hydraulics(
        flow_rate_m3h, pipe_diameter_mm, roughness_mm, 
        fluid_density, fluid_viscosity_cp, pipe_length_m
    )

    # Display KPI Metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Flow Velocity", f"{results['velocity']:.2f} m/s")
    col2.metric("Reynolds Number (Re)", f"{results['reynolds_number']:,.0f}")
    col3.metric("Friction Factor (f)", f"{results['friction_factor']:.4f}")
    col4.metric("Pressure Loss", f"{results['pressure_drop_bar']:.3f} bar", delta=f"{results['pressure_drop_psi']:.2f} psi")

    st.markdown(f"Flow Regime Identified: {results['flow_regime']}")
    st.divider()

    # -------------------------------------------------------------------------
    # PLOTLY SENSITIVITY CHART
    # -------------------------------------------------------------------------
    st.subheader("📈 Parametric Sensitivity Analysis: Pressure Drop vs. Diameter")

    diameters_range, dp_range = generate_diameter_sensitivity(
        flow_rate_m3h, pipe_diameter_mm, roughness_mm, 
        fluid_density, fluid_viscosity_cp, pipe_length_m
    )

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=diameters_range,
        y=dp_range,
        mode='lines',
        name='Pressure Drop (bar)',
        line=dict(color='#0066CC', width=3)
    ))
    
    # Highlight current operating point
    fig.add_trace(go.Scatter(
        x=[pipe_diameter_mm],
        y=[results['pressure_drop_bar']],
        mode='markers',
        name='Current Operating Point',
        marker=dict(color='red', size=12, symbol='diamond')
    ))

    fig.update_layout(
        title="Pipe Diameter vs. Pressure Drop (Fixed Flow Rate & Length)",
        xaxis_title="Pipe Inner Diameter (mm)",
        yaxis_title="Pressure Loss ΔP (bar)",
        template="plotly_white",
        height=450
    )

    st.plotly_chart(fig, use_container_width=True)


    # -------------------------------------------------------------------------
    # PANDAS RESULTS TABLE
    # -------------------------------------------------------------------------
    st.subheader("📊 Hydraulic Results Data Summary Table")

    summary_df = pd.DataFrame({
        "Parameter": [
            "Volumetric Flow Rate (Q)",
            "Pipe Inner Diameter (D)",
            "Pipe Length (L)",
            "Absolute Roughness (ε)",
            "Fluid Density (ρ)",
            "Dynamic Viscosity (μ)",
            "Flow Velocity (v)",
            "Reynolds Number (Re)",
            "Darcy Friction Factor (f)",
            "Pressure Loss (ΔP)"
        ],
        "Value": [
            f"{flow_rate_m3h:.2f}",
            f"{pipe_diameter_mm:.2f}",
            f"{pipe_length_m:.2f}",
            f"{roughness_mm:.4f}",
            f"{fluid_density:.2f}",
            f"{fluid_viscosity_cp:.2f}",
            f"{results['velocity']:.3f}",
            f"{results['reynolds_number']:,.1f}",
            f"{results['friction_factor']:.5f}",
            f"{results['pressure_drop_bar']:.4f}"
        ],
        "Unit": ["m³/h", "mm", "m", "mm", "kg/m³", "cP", "m/s", "Dimensionless", "Dimensionless", "bar"]
    })

    st.dataframe(summary_df, use_container_width=True, hide_index=True)

else:
    st.info("💡 Please adjust the parameters in the sidebar to remove warnings and compute hydraulic outputs.")